<?php

namespace Mawi\Bundle\FrostlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StorageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorageRepository extends EntityRepository
{
}
