jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Mawi\Bundle\FrostlogBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: MawiFrostlogBundle:User, property: username } 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
        secured_area:
            pattern:    ^/
            logout:
                path:   /logout
                target: /login/done
            anonymous:  ~
            form_login:
                check_path: /login_check
                login_path: /login
                failure_path: /login/fail
                always_use_default_target_path: true
                default_target_path: /login/done

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
